// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskR.Data;

#nullable disable

namespace TaskR.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20250602131045_VirtualLists")]
    partial class VirtualLists
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaskR.Data.AppUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("EMail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastLogon")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("RegisteredOn")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("UserRole")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("TaskR.Data.Aufgabe", b =>
                {
                    b.Property<int>("AufgabeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AufgabeId"));

                    b.Property<string>("Beschreibung")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Erledigt")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ErledigtDatum")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ErstelltDatum")
                        .HasColumnType("datetime2");

                    b.Property<int>("Priorität")
                        .HasColumnType("int");

                    b.Property<int>("TodoId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AufgabeId");

                    b.HasIndex("TodoId");

                    b.ToTable("Aufgaben");
                });

            modelBuilder.Entity("TaskR.Data.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TagId"));

                    b.Property<int>("AufgabeId")
                        .HasColumnType("int");

                    b.Property<string>("ColorCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("TagId");

                    b.HasIndex("AufgabeId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("TaskR.Data.Todo", b =>
                {
                    b.Property<int>("TodoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TodoId"));

                    b.Property<DateTime>("ErstellDatum")
                        .HasColumnType("datetime2");

                    b.Property<string>("TodoName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("TodoId");

                    b.HasIndex("UserId");

                    b.ToTable("Todos");
                });

            modelBuilder.Entity("TaskR.Data.Aufgabe", b =>
                {
                    b.HasOne("TaskR.Data.Todo", "Todo")
                        .WithMany("TaskGroup")
                        .HasForeignKey("TodoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Todo");
                });

            modelBuilder.Entity("TaskR.Data.Tag", b =>
                {
                    b.HasOne("TaskR.Data.Aufgabe", "Aufgabe")
                        .WithMany("Tags")
                        .HasForeignKey("AufgabeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aufgabe");
                });

            modelBuilder.Entity("TaskR.Data.Todo", b =>
                {
                    b.HasOne("TaskR.Data.AppUser", "AppUser")
                        .WithMany("TodoList")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("TaskR.Data.AppUser", b =>
                {
                    b.Navigation("TodoList");
                });

            modelBuilder.Entity("TaskR.Data.Aufgabe", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("TaskR.Data.Todo", b =>
                {
                    b.Navigation("TaskGroup");
                });
#pragma warning restore 612, 618
        }
    }
}
